export const USER_LOADED = 'USER_LOADED';
export const USER_LOADING = 'USER_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR ';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS ';
export const REGISTER_FAIL = 'REGISTER_FAIL ';
export const AUTH_LOADING = 'AUTH_LOADING ';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const CREATE_REDFLAG = 'CREATE_REDFLAG';
export const CREATE_FAILED = 'CREATE_FAILED';
export const CREATING = 'CREATING';

export const NETWORK_ERROR = 'NETWORK_ERROR';

export const FETCH_RECORD_REQUEST = 'FETCH_RECORD_REQUEST';
export const FETCH_RECORD_SUCCESS = 'FETCH_RECORD_SUCCESS ';
export const FETCH_RECORD_FAILURE = 'FETCH_RECORD_FAILURE';

export const FETCH_SINGLE_RECORD_SUCCESS = 'FETCH_SINGLE_RECORD_SUCCESS';
export const FETCH_SINGLE_RECORD_REQUEST = 'FETCH_SINGLE_RECORD_SUCCESS ';
export const FETCH_SINGLE_RECORD_FAILURE = 'FETCH_SINGLE_RECORD_FAILURE';
